require File.dirname(__FILE__) + "/automaton/class"
require File.dirname(__FILE__) + "/automaton/plugins"
require File.dirname(__FILE__) + "/automaton/runner"
require File.dirname(__FILE__) + "/automaton/string"
require File.dirname(__FILE__) + "/automaton/terminal"
